POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
    "name": "",
    "occupation": "Unemployed",
    "gender": "male",
    "ssn": "11234456",
    "dateOfBirth": "-01-05"
}
