POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
    "name": "Bob Doe",
    "occupation": "Unemployed",
    "gender": "Male",
    "ssn": "11234456",
    "dateOfBirth": "2000-01-05"
}
