POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root5",
  "name": "root",
  "password": "wow password5"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "chang",
  "name": "chang",
  "password": "changpassword"
}

### Now an invalid user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "it",
  "name": "root",
  "password": "o9ow"
}