GET http://localhost:3003/api/blogs

###
PUT http://localhost:3003/api/blogs/674ffda243521a75
content-type: application/json

{
  "title": "Huggy",
  "author": "Happy Hugger",
  "url": "google.com",
  "likes": "90"
}
