POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root2",
  "name": "root",
  "password": "wow password2"
}

### Now an invalid user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "it",
  "name": "root",
  "password": "o9ow"
}