POST http://localhost:3003/api/blogs/675f88e7535368a7ab5f1d87/comments
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoYW5nIiwiaWQiOiI2Nzg0ODBlMmJmNzAyZDlhNzQxNzk1YzAiLCJpYXQiOjE3MzY4MTQ0ODcsImV4cCI6MTczNjgyODg4N30.O0jzPwqB9pOZo-VyQhuPBIN7BNO74dQ4ol0htsU0o9I

{
  "comment": "This is a comment"
}