GET http://localhost:3002/api/notes/

### bad
POST http://localhost:3002/api/notes/ HTTP/1.1
content-type: application/json

{
    "important": "false"
}

### good
POST https://fullstackopen-example-chang.fly.dev/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "test unimportant note",
    "important": "false"
}