GET http://localhost:3002/api/notes/

### bad
POST http://localhost:3002/api/notes/ HTTP/1.1
content-type: application/json

{
    "important": "false"
}

### good
POST http://localhost:3002/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "test unimportant note",
    "important": "true",
    "userId": "67526fd394b5014b88ce8af0"
}